// apps/web/src/pages/LegalPage.tsx
import { ScrollArea } from '../components/ui/scroll-area';

export function LegalPage() {
  return (
    <div className="container max-w-3xl mx-auto px-4 py-8 pb-24">
      <h1 className="text-3xl font-bold mb-2">Legal Information</h1>
      <p className="text-muted-foreground mb-8">Privacy Policy & Terms of Use</p>

      <div className="space-y-12">
        
        {/* PRIVACY POLICY */}
        <section className="space-y-4">
            <div className="border-b pb-2 mb-4">
                <h2 className="text-2xl font-bold">Privacy Policy</h2>
                <p className="text-sm text-muted-foreground">Last Updated: January 10, 2026</p>
            </div>
            
            <div className="prose dark:prose-invert max-w-none text-sm space-y-4 text-muted-foreground">
                <p>
                    Welcome to <strong>The Gamut</strong>, operated by <strong>Stalingrad Technologies (OPC) Pvt Ltd</strong> ("Company", "we", "our", or "us"). 
                    We respect your privacy and are committed to protecting your personal data.
                </p>

                <h3 className="text-foreground font-semibold text-lg">1. Information We Collect</h3>
                <ul className="list-disc pl-5 space-y-1">
                    <li><strong>Identity Data:</strong> Name, email, and profile pictures via secure auth.</li>
                    <li><strong>Usage Data:</strong> Articles read, time spent, and interactions for personalization.</li>
                    <li><strong>Location Data:</strong> Optional access for local weather updates.</li>
                </ul>

                <h3 className="text-foreground font-semibold text-lg">2. How We Use Your Data</h3>
                <p>To deliver personalized news, generate AI summaries ("Smart Briefs"), and provide emergency services functionality.</p>

                <h3 className="text-foreground font-semibold text-lg">3. Third-Party Services</h3>
                <p>
                    We use trusted providers for Authentication (Firebase), Database (MongoDB/Prisma), and AI processing. 
                    Advertising is served via Google AdSense; you may opt-out of personalized ads via Google Settings.
                </p>

                <h3 className="text-foreground font-semibold text-lg">4. Contact</h3>
                <p>Questions? Email us at: <strong>support@thegamut.in</strong></p>
            </div>
        </section>

        {/* TERMS OF USE */}
        <section className="space-y-4">
            <div className="border-b pb-2 mb-4">
                <h2 className="text-2xl font-bold">Terms of Use</h2>
                <p className="text-sm text-muted-foreground">Last Updated: January 10, 2026</p>
            </div>

            <div className="prose dark:prose-invert max-w-none text-sm space-y-4 text-muted-foreground">
                <p>
                    By accessing <strong>The Gamut</strong>, you agree to these Terms. The application is owned by <strong>Stalingrad Technologies (OPC) Pvt Ltd</strong>.
                </p>

                <h3 className="text-foreground font-semibold text-lg">1. AI Disclaimer</h3>
                <p>
                    Our "Smart Briefs" and audio narratives are generated by Artificial Intelligence. 
                    While we strive for accuracy, AI may occasionally produce errors or hallucinations. 
                    Always verify critical information with original sources.
                </p>

                <h3 className="text-foreground font-semibold text-lg">2. Intellectual Property</h3>
                <p>
                    We do not claim ownership of the original news articles aggregated from third-party sources. 
                    The Gamut's design, code, and specific AI-generated features are our proprietary property.
                </p>

                <h3 className="text-foreground font-semibold text-lg">3. Governing Law</h3>
                <p>
                    These terms are governed by the laws of <strong>India</strong>. 
                    Disputes are subject to the exclusive jurisdiction of courts in <strong>Pune, Maharashtra</strong>.
                </p>
            </div>
        </section>

      </div>
    </div>
  );
}
